### PR TITLE
add support to compile with ngx_mruby module #49

### PR DESCRIPTION
**Pull request by Tei1988**
Hello,

I add ngx_mruby as a new module.

This module extends the config file with mruby.

The official site and repository are listed below:
- http://ngx.mruby.org/
- https://github.com/matsumoto-r/ngx_mruby

I add some codes to 'nginx-full.rb'.
So, please check them.

### CODE REVIEW

**Comment by matsumoto-r** [comment]
:eyes:

**Comment by mikemcquaid** [comment]
@denji Can you elaborate a bit? I'm not sure I understand.

**Comment by Tei1988** [comment]
@denji
> homebrew/nginx/nginx-full:
>  * Don't need 'FileUtils.' before rm_rf.

I corrected it.

**Comment by denji** [comment]
@Tei1988 @matsumoto-r https://github.com/Homebrew/homebrew-nginx/commit/a20b72aa07ce2750cdd5f4129243cd19332683b0

**Pull request closed without merging**
