### PR TITLE
Create vod-nginx-module.rb

### PR DESCRIPTION
**Pull request by mtoschi**

### CODE REVIEW

**Comment by mtoschi** [comment]
Removed version "1.4" but would prefer latest commit branch to tagged branch unless that's faux pas.

**Comment by denji** [comment]
@mtoschi You can use the patches `https://github.com/kaltura/nginx-vod-module/compare/5cbed41...master.diff`.

Also, you didn't specify the version URL `https://github.com/kaltura/nginx-vod-module/archive/1.4.tar.gz`

**Comment by mtoschi** [comment]
All right, using the tag version and patching the diff. Hope it's right now.

**Comment by denji** [comment]
LGTM thanks, merged!

**Pull request merged**
